// Generated by Copilot.
export const followers = [
  {
    userId: 1,
    followerId: 2,
  },
  {
    userId: 1,
    followerId: 3,
  },
  {
    userId: 2,
    followerId: 1,
  },
  {
    userId: 2,
    followerId: 3,
  },
  {
    userId: 3,
    followerId: 1,
  },
  {
    userId: 3,
    followerId: 2,
  },
];
