version: '3.1'

services:
  db:
    image: postgres:16.2-alpine3.19
    container_name: umzug-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    # volumes:
    #   - ./data:/var/lib/postgresql/data
